// <auto-generated />
using System;
using CurriculumVitae.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurriculumVitae.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240818135148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CurriculumVitae.Shared.DtoModels.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactInformationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactInformationId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CurriculumVitae.Shared.DtoModels.ContactInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLineOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLineTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactInformation");
                });

            modelBuilder.Entity("CurriculumVitae.Shared.DtoModels.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContactInformationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactInformationId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("CurriculumVitae.Shared.DtoModels.Company", b =>
                {
                    b.HasOne("CurriculumVitae.Shared.DtoModels.ContactInformation", "ContactInformation")
                        .WithMany()
                        .HasForeignKey("ContactInformationId");

                    b.Navigation("ContactInformation");
                });

            modelBuilder.Entity("CurriculumVitae.Shared.DtoModels.Phone", b =>
                {
                    b.HasOne("CurriculumVitae.Shared.DtoModels.ContactInformation", null)
                        .WithMany("Phones")
                        .HasForeignKey("ContactInformationId");
                });

            modelBuilder.Entity("CurriculumVitae.Shared.DtoModels.ContactInformation", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
